# Generated by Django 5.2.6 on 2026-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
