# Generated by Django 5.2.4 on 2026-01-04 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_order_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
